### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by anondev-sudo** [afnan007a/Ptero-vm#10]
![image](https://user-images.githubusercontent.com/85408287/139421223-1b3e1829-e618-46a3-ae36-0728e75fc70f.png)

**Comment by RealTriassic** [comment]
Most likely the docker image the host is using does not have "curl" installed.

**Comment by anondev-sudo** [comment]
Can the script install it?

**Comment by afnan007a** [comment]
If the image don't have curl then try wget (usually wget or curl will be there by default
