### ISSUE TITLE
404

### ISSUE THREAD

**Issue by DarkerInker** [afnan007a/Ptero-vm#12]
https://transfer.sh/get/kqSsML/unzip returns 404 not found, you prob should fix that lmao (if you can ofc)

**Comment by afnan007a** [comment]
> https://transfer.sh/get/kqSsML/unzip returns 404 not found, you prob should fix that lmao (if you can ofc)

i dont owns unzip but let me try ig

**Comment by afnan007a** [comment]
fixed

**Comment by afnan007a** [comment]
thanks for informing the issue!
