### ISSUE TITLE
I'm creator of some scripts which you edited to another... But why?

### ISSUE THREAD

**Issue by werasik2aa** [afnan007a/Ptero-vm#19]
https://igriastranomier.ucoz.ru/apth.txt
Very same But my date is older then your
![image](https://user-images.githubusercontent.com/20810116/145001673-e033bca2-483c-4704-b8a2-1e4dede84583.png)
Can you say who give it to you?
and some your script start as mine
![image](https://user-images.githubusercontent.com/20810116/145001866-d576be7b-44da-4050-86a7-5bcea0dde6af.png)
Why?
My DS nopirateonlysteam#9956

**Comment by werasik2aa** [comment]
![image](https://user-images.githubusercontent.com/20810116/145002018-e1d3ba32-4653-4183-984e-8713a5d76b11.png)

**Comment by afnan007a** [comment]
oh about the apth, actually a friend of mine gave me the apth.txt i dont know how he got it (ps he give it to me via discord, i think i have ss of it) i never claimed 'apth" as mine. if u check the license below i dont even claim pterovm cuz it is a damage causing script and i dont want to get in any kind of drama

**Comment by afnan007a** [comment]
https://share-x.redknight.xyz/u/ppbvs44.png

**Comment by afnan007a** [comment]
why the hell i closed this

**Comment by afnan007a** [comment]
ps, 'apth' is not part of the script it is only used to install the required packages to run pterovm without root cuz some host dont even have `install pkg` so yeah

**Comment by chirag350** [comment]
Hi
Don't forget that apth is not licensed and is open source

**Comment by werasik2aa** [comment]
chirag350 ...
The "apth" file has not been published in any of the github repositories. So who told so?
