### ISSUE TITLE
its stuck on 60%

### ISSUE THREAD

**Issue by duckytutorials** [afnan007a/Ptero-vm#20]
it is downloading and its sttuck on 60%

**Comment by afnan007a** [comment]
whats the resources u gave?

**Comment by XiaoSha-0711** [comment]
4GB RAM, 200%CPU 200GB Disk

发自我的iPhone

**Comment by afnan007a** [comment]
do u still face the issue?

**Comment by BasToTheMax** [comment]
I have this issue too :(
