### ISSUE TITLE
like VM root access?

### ISSUE THREAD

**Issue by dgcardoso** [afnan007a/Ptero-vm#21]
How do I access the VM's SSH root? is it working correctly and what operating system is installed?

**Comment by afnan007a** [comment]
kindly read the readme, it uses debian. u can access the server via ptero console, if u want to get ssh access, just run openssh-server in the server and connect it with the port you provided

**Comment by dgcardoso** [comment]
what is the root username and password?

**Comment by afnan007a** [comment]
...
