### ISSUE TITLE
Error when running NodeJS apps and "Aw snap" bug on Chromium

### ISSUE THREAD

**Issue by ItzCuteAkemi** [afnan007a/Ptero-vm#26]
I have PteroVM installation on my server. When I run `npm`, this is what I got
```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/usr/bin/npm'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
Also when I started Chromium as non-root user (created another user in PteroVM), I got "Aw snap" bug with error signal "SIGTRAP" (this will happen if you open some website or multiple tabs.
![anydesk00000](https://user-images.githubusercontent.com/91181632/179393563-dabcf2f1-e8f0-47b0-9fa7-d5abf34c21a5.png)

So how to fix it?
Note: I run AnyDesk inside PteroVM

**Comment by ItzCuteAkemi** [comment]
@afnan007a

**Comment by afnan007a** [comment]
have u installed npm in the server? and about the anydesk. i never tried it before. it maybe because of the ram usage

**Comment by ItzCuteAkemi** [comment]
> have u installed npm in the server? and about the anydesk. i never tried it before. it maybe because of the ram usage

yes I have it installed. The ram usage is only around 1.5GB at idle with 8GB ram allocation

**Comment by ItzCuteAkemi** [comment]
@afnan007a also I use java egg

**Comment by afnan007a** [comment]
egg? did u mean the jar?, i never tried anydesk inside pterovm so i have no idea

**Comment by afnan007a** [comment]
contact me on discord if u wanna talk more about it Afnan#4804

**Comment by ItzCuteAkemi** [comment]
Sent friend request
