### ISSUE TITLE
proot error: ptrace(TRACEME): Operation not permitted

### ISSUE THREAD

**Issue by ArtichautLearnCode** [afnan007a/Ptero-vm#27]
Default@Ptero-vm:~ htop
proot error: ptrace(TRACEME): Operation not permitted
proot error: execve("/bin/bash"): Operation not permitted
proot info: It seems your kernel contains this bug: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1202161
To workaround it, set the env. variable PROOT_NO_SECCOMP to 1.
fatal error: see `proot --help`.
proot error: can't chmod '/tmp/proot-136-Mi86Fj': No such file or directory

with the server.jar

**Comment by afnan007a** [comment]
which host

**Comment by ArtichautLearnCode** [comment]
Debian 11 classic with classic pterodactyl

**Comment by ArtichautLearnCode** [comment]
Java 8 image

**Comment by ArtichautLearnCode** [comment]
> which host

Self Host :)
Debian 11
Ptérodactyl 1.10.1
Wings 1.7
Java 8 image

**Comment by afnan007a** [comment]
the java version of pterovm is not maintained by me, i recommend u to use either js or py
