### ISSUE TITLE
Trouble

### ISSUE THREAD

**Issue by kinseyy** [afnan007a/Ptero-vm#30]
![2022-09-27_23-17-17](https://user-images.githubusercontent.com/86409467/192616126-6b37e93b-31ae-43af-a0c8-54ee5cde3b20.png)
In pterodactyl , I cant see more in console... 
How do I can check ngrok port forward?

**Comment by afnan007a** [comment]
its because pterodactyl dont having a real time console its not pterovm's fault. its pteros i have no way to fix it
